DROP SEQUENCE IF EXISTS CARD_SEQ ;
CREATE SEQUENCE CARD_SEQ START WITH 1 INCREMENT BY 1;
DROP TABLE IF EXISTS CREDIT_CARD_DATA ;

CREATE TABLE CREDIT_CARD_DATA (ID BIGINT default CARD_SEQ.nextval PRIMARY KEY, NAME VARCHAR(255), CARD_NUMBER VARCHAR(19), CARD_BALANCE DECIMAL(20, 2) , CARD_LIMIT DECIMAL(20, 2));
